spring:
  application:
    name: loadTestApplication

  datasource:
    url: jdbc:postgresql://localhost:5432/loadtest
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

# CORS ?? ??
spring.web.cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  allow-credentials: false

loadtest:
  max-virtual-threads: 50000
  max-platform-threads: 500
  http-client:
    connect-timeout: 10s
    request-timeout: 30s

